In [24]:
import pandas as pd
import numpy as np

In [25]:
df=pd.read_csv(r"../data/city_hour.csv")

In [26]:
df.head()

,City,Datetime,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,Xylene,AQI,AQI_Bucket
0,Delhi,2015-01-01 00:00:00,258.0,340.6,191.0,13.4,104.1,16.2,1.15,39.8,70.4,11.64,10.23,1.95,411.5,Moderate
1,Mumbai,2015-01-01 00:00:00,120.1,47.9,165.3,57.9,139.2,14.4,0.76,3.3,23.2,11.35,11.38,1.53,134.8,Poor
2,Chennai,2015-01-01 00:00:00,130.1,375.0,21.9,23.7,205.6,33.6,3.50,63.0,138.9,16.30,24.07,0.56,329.6,Poor
3,Kolkata,2015-01-01 00:00:00,189.1,174.3,139.7,58.9,103.7,19.2,0.81,3.3,14.6,5.12,1.42,2.35,351.9,Good
4,Bangalore,2015-01-01 00:00:00,357.8,48.8,121.2,83.3,8.3,11.9,6.31,67.4,195.9,15.12,16.80,8.95,23.7,Moderate

In [27]:
df = df[df["City"] == "Delhi"].copy()

df["Datetime"] = pd.to_datetime(df["Datetime"])

df = df.sort_values("Datetime").reset_index(drop=True)

df.drop(columns=['City','AQI_Bucket'],inplace=True)

df.head()

,Datetime,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,Xylene,AQI
0,2015-01-01 00:00:00,258.0,340.6,191.0,13.4,104.1,16.2,1.15,39.8,70.4,11.64,10.23,1.95,411.5
1,2015-01-01 01:00:00,463.8,516.5,19.4,81.1,57.6,35.6,6.33,62.3,193.6,14.60,4.44,7.36,22.9
2,2015-01-01 02:00:00,100.9,225.8,151.5,5.9,162.4,33.6,2.06,47.5,121.0,5.35,29.01,7.63,493.7
3,2015-01-01 03:00:00,364.9,318.5,33.6,81.7,8.5,17.9,0.42,62.2,125.6,8.71,29.66,5.85,125.9
4,2015-01-01 04:00:00,30.2,106.2,155.3,48.6,16.0,43.5,4.94,82.1,62.0,4.17,5.63,2.82,170.3